### ISSUE TITLE
Add why to learn Rust even

### ISSUE THREAD

**Issue by tanuj101** [pepsighan/rust-web-developer-roadmap#1]

**Comment by pepsighan** [comment]
This repo is all about the **hows** of learning Rust in the web dev context as is with the [Golang Developer Roadmap](https://github.com/Alikhll/golang-developer-roadmap) which this work is based on. 

The why? of it is not something I want to explore and will leave it to the developer to figure out.

**Comment by tanuj101** [comment]
Yeah I saw that repo, but I think why part should be there too
